# Generated by Django 4.2.1 on 2023-05-25 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=' ', max_length=60)),
                ('last_name', models.CharField(default=' ', max_length=60)),
                ('cpf', models.CharField(default=' ', max_length=60)),
                ('email', models.EmailField(default=' ', max_length=254)),
                ('telefone', models.CharField(default=' ', max_length=20)),
                ('password', models.CharField(default=' ', max_length=40)),
            ],
        ),
    ]
